---
apiVersion: v1
kind: Service
metadata:
  name: tidb-external
  labels:
    app: basic-tidb
spec:
  type: NodePort
  ports:
  - name: 'tidb-port'
    port: 4000
    targetPort: 4000
    protocol: TCP
  selector:
    app.kubernetes.io/component: tidb
    app.kubernetes.io/instance: basic
    app.kubernetes.io/managed-by: tidb-operator
    app.kubernetes.io/name: tidb-cluster
