apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  initContainers:
  - name: install
    image: busybox
    command: 
      - "sh"
      - "-c"
      - |
        echo 'hello'> /work-dir/index.html
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
    resources:
      limits:
        memory: 500Mi
        cpu: 250m   
  dnsPolicy: Default
  volumes:
  - name: workdir
    emptyDir: {}
