apiVersion: v1
kind: Service
metadata:
  name: hostnames
spec:
  # type: NodePort
  selector:
    app: hostnames
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 9376
  #  nodePort: 30080
  # externalIPs:
  # - 172.16.16.200
