apiVersion: v1
kind: Service
metadata:
  labels:
    role: mongo
  name: mongo-nodeport-svc
  namespace: mongo
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    role: mongo
  type: NodePort
status:
  loadBalancer: {}