apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 0cf2e4ae6a-ifg48.cn-hangzhou.nas.aliyuncs.com
    path: /